databases:
  - name: mmablog
    plan: free
    databaseName: mmablog
    user: mm1

services:
  - type: web
    plan: free
    name: mmablog
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mmablogproject.asgi:application"
    # envVars:
    #   - key: "postgres://mm1:DxeUX4eMsz9osDF01nKPphT1TbFUFQ9K@dpg-co73t46n7f5s738g235g-a/mmablog"
    #     fromDatabase:
    #       name: mmablog
    #       property: connectionString
    #   - key: SECRET_KEY
    #     generateValue: true
    #   - key: WEB_CONCURRENCY
    #     value: 4